--
-- PostgreSQL database dump
--



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--



--
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: -
--



SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: features_v1; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.features_v1 (
    "time" timestamp with time zone NOT NULL,
    ticker text NOT NULL,
    timeframe text NOT NULL,
    feature text NOT NULL,
    value double precision
);


--
-- Name: backtests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.backtests (
    id bigint NOT NULL,
    model_id bigint,
    strategy text NOT NULL,
    ticker text NOT NULL,
    range_start timestamp with time zone NOT NULL,
    range_end timestamp with time zone NOT NULL,
    params jsonb NOT NULL,
    metrics jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: backtests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.backtests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backtests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: candles_1d_1h; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candles_1d_1h (
    "time" timestamp with time zone NOT NULL,
    ticker text NOT NULL,
    symbol text,
    open double precision NOT NULL,
    high double precision NOT NULL,
    low double precision NOT NULL,
    close double precision NOT NULL,
    volume double precision DEFAULT 0 NOT NULL,
    ask_volume double precision DEFAULT 0 NOT NULL,
    bid_volume double precision DEFAULT 0 NOT NULL,
    cvd_open double precision,
    cvd_high double precision,
    cvd_low double precision,
    cvd_close double precision,
    vd double precision,
    vd_ratio double precision,
    book_imbalance double precision,
    price_pct double precision,
    divergence double precision,
    trades integer DEFAULT 0 NOT NULL,
    max_trade_size double precision DEFAULT 0 NOT NULL,
    big_trades integer DEFAULT 0 NOT NULL,
    big_volume double precision DEFAULT 0 NOT NULL,
    sum_bid_depth double precision DEFAULT 0 NOT NULL,
    sum_ask_depth double precision DEFAULT 0 NOT NULL,
    sum_price_volume double precision DEFAULT 0 NOT NULL,
    unknown_volume double precision DEFAULT 0 NOT NULL
);


--
-- Name: candles_1h_1m; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candles_1h_1m (
    "time" timestamp with time zone NOT NULL,
    ticker text NOT NULL,
    symbol text,
    open double precision NOT NULL,
    high double precision NOT NULL,
    low double precision NOT NULL,
    close double precision NOT NULL,
    volume double precision DEFAULT 0 NOT NULL,
    ask_volume double precision DEFAULT 0 NOT NULL,
    bid_volume double precision DEFAULT 0 NOT NULL,
    cvd_open double precision,
    cvd_high double precision,
    cvd_low double precision,
    cvd_close double precision,
    vd double precision,
    vd_ratio double precision,
    book_imbalance double precision,
    price_pct double precision,
    divergence double precision,
    trades integer DEFAULT 0 NOT NULL,
    max_trade_size double precision DEFAULT 0 NOT NULL,
    big_trades integer DEFAULT 0 NOT NULL,
    big_volume double precision DEFAULT 0 NOT NULL,
    sum_bid_depth double precision DEFAULT 0 NOT NULL,
    sum_ask_depth double precision DEFAULT 0 NOT NULL,
    sum_price_volume double precision DEFAULT 0 NOT NULL,
    unknown_volume double precision DEFAULT 0 NOT NULL
);


--
-- Name: candles_1m_1s; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.candles_1m_1s (
    "time" timestamp with time zone NOT NULL,
    ticker text NOT NULL,
    open double precision NOT NULL,
    high double precision NOT NULL,
    low double precision NOT NULL,
    close double precision NOT NULL,
    volume double precision DEFAULT 0,
    ask_volume double precision DEFAULT 0,
    bid_volume double precision DEFAULT 0,
    cvd_open double precision,
    cvd_high double precision,
    cvd_low double precision,
    cvd_close double precision,
    vd double precision,
    trades integer DEFAULT 0 NOT NULL,
    max_trade_size double precision DEFAULT 0 NOT NULL,
    big_trades integer DEFAULT 0 NOT NULL,
    big_volume double precision DEFAULT 0 NOT NULL,
    symbol text,
    vd_ratio double precision,
    book_imbalance double precision,
    price_pct double precision,
    divergence double precision,
    sum_bid_depth double precision DEFAULT 0 NOT NULL,
    sum_ask_depth double precision DEFAULT 0 NOT NULL,
    sum_price_volume double precision DEFAULT 0 NOT NULL,
    unknown_volume double precision DEFAULT 0 NOT NULL
);


--
-- Name: models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.models (
    id bigint NOT NULL,
    name text NOT NULL,
    version text NOT NULL,
    params jsonb NOT NULL,
    metrics jsonb NOT NULL,
    artifact_uri text,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: predictions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.predictions (
    "time" timestamp with time zone NOT NULL,
    model_id bigint NOT NULL,
    ticker text NOT NULL,
    prediction double precision NOT NULL,
    label double precision
);


--
-- Name: backtests backtests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backtests
    ADD CONSTRAINT backtests_pkey PRIMARY KEY (id);


--
-- Name: candles_1d_1h candles_1d_1h_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candles_1d_1h
    ADD CONSTRAINT candles_1d_1h_pkey PRIMARY KEY (ticker, "time");


--
-- Name: candles_1h_1m candles_1h_1m_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candles_1h_1m
    ADD CONSTRAINT candles_1h_1m_pkey PRIMARY KEY (ticker, "time");


--
-- Name: candles_1m_1s candles_1m_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.candles_1m_1s
    ADD CONSTRAINT candles_1m_pkey PRIMARY KEY (ticker, "time");


--
-- Name: features_v1 features_v1_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.features_v1
    ADD CONSTRAINT features_v1_pkey PRIMARY KEY (ticker, timeframe, feature, "time");


--
-- Name: models models_name_version_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_name_version_key UNIQUE (name, version);


--
-- Name: models models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.models
    ADD CONSTRAINT models_pkey PRIMARY KEY (id);


--
-- Name: predictions predictions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.predictions
    ADD CONSTRAINT predictions_pkey PRIMARY KEY (model_id, ticker, "time");


--
-- Name: idx_backtests_strategy_ticker; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_backtests_strategy_ticker ON public.backtests USING btree (strategy, ticker);


--
-- Name: idx_candles_1d_1h_time_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_candles_1d_1h_time_desc ON public.candles_1d_1h USING btree ("time" DESC);


--
-- Name: idx_candles_1h_1m_time_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_candles_1h_1m_time_desc ON public.candles_1h_1m USING btree ("time" DESC);


--
-- Name: idx_candles_1m_1s_time_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_candles_1m_1s_time_desc ON public.candles_1m_1s USING btree ("time" DESC);


--
-- Name: idx_features_v1_time_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_features_v1_time_desc ON public.features_v1 USING btree ("time" DESC);


--
-- Name: idx_predictions_time_desc; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_predictions_time_desc ON public.predictions USING btree ("time" DESC);


--
-- Name: backtests backtests_model_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.backtests
    ADD CONSTRAINT backtests_model_id_fkey FOREIGN KEY (model_id) REFERENCES public.models(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


