-- 202605072300__add_backtest_python_tables.sql
-- Adds the downstream research tables owned by `apps/backtest-python`.
--
-- Boundary: `apps/write-node` continues to own canonical candle tables
-- (`candles_1m_1s`, `candles_1h_1m`, `candles_1d_1h`). It never reads or writes
-- the tables added here. `apps/backtest-python` is the only writer of these
-- four tables; consumers like `view-next` are read-only.
--
-- Tables:
--   features_v1  — long-format derived feature timeseries (hypertable)
--   models       — model registry (params, metrics, artifact location)
--   backtests    — backtest run summaries (params, metrics)
--   predictions  — model predictions per (ticker, time) (hypertable)
--
-- Layout choices:
--   features_v1 uses long format keyed by (ticker, timeframe, feature, "time")
--   so new features can be added without migrations. compress_segmentby on
--   (ticker, timeframe, feature) keeps each series tightly compressed.
--
--   predictions is keyed by (model_id, ticker, "time") so multiple models can
--   coexist for the same ticker. Compression segments by model_id and ticker
--   for similar reasons.

-- ---------------------------------------------------------------------------
-- features_v1
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.features_v1 (
    "time" timestamp with time zone NOT NULL,
    ticker text NOT NULL,
    timeframe text NOT NULL,
    feature text NOT NULL,
    value double precision,
    CONSTRAINT features_v1_pkey PRIMARY KEY (ticker, timeframe, feature, "time")
);

CREATE INDEX IF NOT EXISTS idx_features_v1_time_desc
    ON public.features_v1 USING btree ("time" DESC);

SELECT create_hypertable(
    'public.features_v1',
    by_range('time', INTERVAL '1 month'),
    if_not_exists => TRUE,
    create_default_indexes => FALSE
);

ALTER TABLE public.features_v1 SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'ticker, timeframe, feature',
    timescaledb.compress_orderby = 'time DESC'
);

SELECT add_compression_policy(
    'public.features_v1',
    compress_after => INTERVAL '3 months',
    if_not_exists => TRUE
);

-- ---------------------------------------------------------------------------
-- models
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.models (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    name text NOT NULL,
    version text NOT NULL,
    params jsonb NOT NULL,
    metrics jsonb NOT NULL,
    artifact_uri text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT models_pkey PRIMARY KEY (id),
    CONSTRAINT models_name_version_key UNIQUE (name, version)
);

-- ---------------------------------------------------------------------------
-- backtests
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.backtests (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    model_id bigint,
    strategy text NOT NULL,
    ticker text NOT NULL,
    range_start timestamp with time zone NOT NULL,
    range_end timestamp with time zone NOT NULL,
    params jsonb NOT NULL,
    metrics jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT backtests_pkey PRIMARY KEY (id),
    CONSTRAINT backtests_model_id_fkey FOREIGN KEY (model_id)
        REFERENCES public.models (id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_backtests_strategy_ticker
    ON public.backtests USING btree (strategy, ticker);

-- ---------------------------------------------------------------------------
-- predictions
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.predictions (
    "time" timestamp with time zone NOT NULL,
    model_id bigint NOT NULL,
    ticker text NOT NULL,
    prediction double precision NOT NULL,
    label double precision,
    CONSTRAINT predictions_pkey PRIMARY KEY (model_id, ticker, "time")
);

CREATE INDEX IF NOT EXISTS idx_predictions_time_desc
    ON public.predictions USING btree ("time" DESC);

SELECT create_hypertable(
    'public.predictions',
    by_range('time', INTERVAL '1 month'),
    if_not_exists => TRUE,
    create_default_indexes => FALSE
);

ALTER TABLE public.predictions SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'model_id, ticker',
    timescaledb.compress_orderby = 'time DESC'
);

SELECT add_compression_policy(
    'public.predictions',
    compress_after => INTERVAL '3 months',
    if_not_exists => TRUE
);
