#!/bin/sh
set -e # Exit immediately if a command exits with a non-zero status.
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)

if [ "$BRANCH_NAME" = "main" ] || [ "$BRANCH_NAME" = "dev" ]; then
  echo "On 'main' or 'dev' branch, running pre-push checks..."
  npx turbo run test
else
  echo "Not on 'main' or 'dev' branch, skipping pre-push checks."
fi